services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - /opt/homeassistant/app:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /opt/homeassistant/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  mqtt:
    container_name: mqtt-broker
    image: eclipse-mosquitto:2.0
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - "/opt/homeassistant/mqtt:/mosquitto"
      - /etc/localtime:/etc/localtime:ro
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    ports:
      - 8080:8080
    volumes:
      - /opt/homeassistant/z2m:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee_gw:/dev/zigbee_gw
